name: InvalidBloodFX
main: invalidteam\invalidbloodfx\Main
api: 3.0.0
version: 1.0
website: https://github.com/Pedhot-Dev/BloodFX
author: InvalidTeam
authors:
  - PedhotDev

commands:
  bloodfx:
    description: "InvalidBloodFX commands"
    permission: bloodfx.cmd
    aliases:
      - bfx

permissions:
  bloodfx.cmd:
    default: op
    description: "Permission to use all command in InvalidBloodFX"
    children:
      bloodfx.cmd.help:
        description: "Permission to use /bloodfx help command"
        default: op
      bloodfx.cmd.reload:
        description: "Permission to use /bloodfx reload command"
        default: op